name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  sanity:
    strategy:
      matrix:
        ansible_version:
          - stable-2.10
        python_version:
          - 3.8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ansible_collections/xcezx/mackerel

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install ansible-base
        run: pip install git+https://github.com/ansible/ansible.git@${{ ansible_version }} --disable-pip-version-check

      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color --python ${{ matrix.python_version }}
        working-directory: ./ansible_collections/xcezx/mackerel
