name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible:
          - stable-2.10
          - stable-2.11
        python:
          - 3.8
    steps:
      - uses: actions/checkout@v2
        with:
          path: ansible_collections/xcezx/mackerel

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install ansible-base (${{matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color --python ${{ matrix.python }}
        working-directory: ./ansible_collections/xcezx/mackerel
